# Generated by Django 5.2.4 on 2025-08-05 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeProjet',
            fields=[
                ('idGroupe', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('exnom', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('coordonnees', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('DateModification', models.DateField(blank=True, null=True)),
                ('ObjetP', models.CharField(max_length=150, unique=True)),
                ('MontantDetailEst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('IDProjetdeControle', models.IntegerField(default=0)),
                ('DélaisExecution', models.IntegerField(default=0)),
                ('DateCreation', models.DateField(blank=True, null=True)),
                ('Etat_Projet', models.CharField(choices=[(1, 'En cours'), (2, 'Non Lancé'), (3, 'Cloturée'), (4, 'Annulé')], default='En cours', max_length=50)),
                ('Type_Projet', models.CharField(choices=[(1, 'Etudes'), (2, 'Travaux'), (3, 'Services')], default='Travaux', max_length=50)),
                ('IDCreatedBy', models.ForeignKey(blank=True, help_text="Référence de l'utilisateur ayant crée le projet", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projets', to=settings.AUTH_USER_MODEL)),
                ('IDOuvrages', models.ForeignKey(blank=True, help_text='Ouvrage associé au projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='Projects.ouvrage')),
                ('IDProjetParent', models.ForeignKey(blank=True, help_text='Référence du projet parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_projets', to='Projects.projet')),
                ('idChargéAff', models.ForeignKey(blank=True, help_text="Référence de l'utilisateur chargé d'affaire du projet", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affecte_projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marché',
            fields=[
                ('idMarché', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateModification', models.DateField(blank=True, null=True)),
                ('DateCreation', models.DateField(blank=True, null=True)),
                ('DateApprobation', models.DateField(blank=True, null=True)),
                ('ObjetMarché', models.CharField(blank=True, max_length=250, null=True)),
                ('numeroMarché', models.CharField(blank=True, max_length=50, null=True)),
                ('MontantEstMO', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('SAV_InteretsMoratoire', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('SAV_RevisionPrix', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('Forme_Marché', models.CharField(blank=True, max_length=50, null=True)),
                ('Caractère_Prix', models.CharField(blank=True, choices=[(1, 'Prix ferme'), (2, 'Prix révisable'), (3, 'Prix ajustable')], max_length=50, null=True)),
                ('Mode_Passation', models.CharField(blank=True, choices=[(1, "Appel d'offres ouvert"), (2, "Appel d'offres restreint"), (3, 'Consultation'), (4, 'Marché de gré à gré'), (5, 'Autre')], max_length=50, null=True)),
                ('NumArtDélais', models.CharField(blank=True, max_length=12, null=True)),
                ('IDEntitésAdmin', models.BigIntegerField(blank=True, null=True)),
                ('ImpDélaisDansOSetPv', models.BooleanField(default=False)),
                ('CautionProv', models.CharField(blank=True, max_length=50, null=True)),
                ('ImDélaisGlobal', models.BooleanField(default=False)),
                ('IdArchiveDocs', models.BigIntegerField(blank=True, null=True)),
                ('IDGroupeProjets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marchés', to='Projects.groupeprojet')),
                ('IDProjet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marchés', to='Projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffres',
            fields=[
                ('idAO', models.BigAutoField(primary_key=True, serialize=False)),
                ('DateModification', models.DateField(blank=True, null=True)),
                ('DateCreation', models.DateField(blank=True, null=True)),
                ('ObjetAO', models.CharField(blank=True, max_length=250, null=True)),
                ('NumAO', models.CharField(blank=True, max_length=50, null=True)),
                ('DateOuvPlis', models.DateField(blank=True, null=True)),
                ('reservePME', models.BooleanField(default=False)),
                ('CréditPaim', models.CharField(blank=True, max_length=50, null=True)),
                ('CréditEng', models.CharField(blank=True, max_length=50, null=True)),
                ('PlansType', models.CharField(blank=True, max_length=25, null=True)),
                ('PlansNmbre', models.CharField(blank=True, max_length=30, null=True)),
                ('PlansForma', models.CharField(blank=True, max_length=12, null=True)),
                ('NoteTech', models.BooleanField(default=False)),
                ('CertifQualif', models.BooleanField(default=False)),
                ('CertifQualifActivité', models.CharField(blank=True, max_length=50, null=True)),
                ('CertifQualifDomaine', models.CharField(blank=True, max_length=50, null=True)),
                ('CertifQualifQualif', models.CharField(blank=True, max_length=50, null=True)),
                ('CertfifAgréement', models.CharField(blank=True, max_length=50, null=True)),
                ('VisiteLieux', models.BooleanField(default=False)),
                ('VisitelieuDate', models.DateField(blank=True, null=True)),
                ('VisiteLieuxLieu', models.CharField(blank=True, max_length=50, null=True)),
                ('Echantillons', models.CharField(blank=True, max_length=50, null=True)),
                ('IdProjet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_offres', to='Projects.projet')),
            ],
        ),
    ]
